### ISSUE TITLE
max bots is 1000

### ISSUE THREAD

**Issue by XynthX** [crpmax/mc-bots#30]
max bots is 1000
anything higher just wont join, no matter how long I wait

**Comment by crpmax** [comment]
Hello,
there is not any hardcoded limit.

You need to understand that 1000 bots simultaneously connected is very intensive.
My app is not optimized for this high count, because it handles every bot in new thread.
There can be numerous other limitations with this count.
Depending on your system, there can be for example limit of connections or limit of threads the system can handle.

However, can you please provide me the command you used to run my app?
The console log (output from the app)?
Can you try to run multiple instances of the app? (Run it in more terminals or in [screen](https://linuxize.com/post/how-to-use-linux-screen/))

Also, you can try to run multiple instances of my [minecraft-bot-flood](https://github.com/crpmax/minecraft-bot-flood),
which is more optimized for connecting large amounts of bots fast, but the bots can not be controlled.

**Comment by XynthX** [comment]
My command was: java -Xms32768M -Xmx32768M -jar mc-bots-1.2.1.jar -s 127.0.0.1:25565 -d 0 1 -c 2000 -x
and I can't figure out how to enable OpenSSL in php

**Comment by crpmax** [comment]
Ok, I will try to reproduce it and find possible solutions.
Also, I will modify the minecraft-bot-flood to not use OpenSSL.

**Comment by crpmax** [comment]
I tried to run my app with `java -jar mc-bots-1.2.1.jar -s 127.0.0.1 -c 1500 -d 250 300 -x`
and it successfully connected all 1500 bots
![WindowsTerminal_2022-05-29_13-36-07](https://user-images.githubusercontent.com/38163280/170869577-71cb4f36-72d2-4307-bf49-5905b09cd34c.png)

So you can try to increase the connection delay and if it does not help, you can try to:

- Make sure the server itself is not limiting the amount of bots - make sure you have `max-players` set correctly.
- Make sure the server is not very overloaded, or the connections will start dropping
- If you are on Linux, you can try increasing the connection limit with `ulimit -n 4000` (more[ here](https://stackoverflow.com/questions/410616/increasing-the-maximum-number-of-tcp-ip-connections-in-linux))
