### ISSUE TITLE
How to use proxy?

### ISSUE THREAD

**Issue by BloodLetters** [crpmax/mc-bots#32]
i want stress test my server but that only join from my ip not from proxy. i setup a startup correctly using proxy. but not working
can give me some example?

**Comment by crpmax** [comment]
Hello,
use parameters `-t` for proxy type and `-l` for proxy list file.  
For example: with command `java -jar mcbots.jar -s localhost -t socks5 -l proxies.txt` you should have a file proxies.txt where is on each line one socks5 proxy address and port.  
Make sure you are using anonymous or elite proxies!
Otherwise your ip will be exposed even if connecting through the proxy.
You can find many proxy lists online, just search for it on google, or use a proxy scraper.

**Comment by BloodLetters** [comment]
> Hello, use parameters `-t` for proxy type and `-l` for proxy list file. For example: with command `java -jar mcbots.jar -s localhost -t socks5 -l proxies.txt` you should have a file proxies.txt where is on each line one socks5 proxy address and port. Make sure you are using anonymous or elite proxies! Otherwise your ip will be exposed even if connecting through the proxy. You can find many proxy lists online, just search for it on google, or use a proxy scraper.

ohh i see. thats work. thx
