### ISSUE TITLE
Unable to send commands and messages

### ISSUE THREAD

**Issue by ByYaoTang** [crpmax/mc-bots#36]
After entering the server with the robot, enter the registration command but display "please enable chat" and "chat is disabled in the client". How can I turn it on

**Comment by crpmax** [comment]
Hello,
can you please provide the actual output from my app ?
It looks like it's a problem on the server you are connected to, because my app doesn't have these messages.

**Comment by ByYaoTang** [comment]
> 您好，您能提供我的应用程序的实际输出吗？这看起来像是你连接到的服务器上的问题，因为我的应用没有这些消息。
![QQ截图20220726221824](https://user-images.githubusercontent.com/108998716/181029114-f5937b46-b6a1-4cf5-b808-2d21a4cd5b2e.png)

**Comment by crpmax** [comment]
Thanks for sending the output.

It is clear that the error message comes from the server, as it is prefixed with `CHAT |`.
Please make sure, you are using the right command. The server says you should use `/register`, but you are using `/reg` only, I know this is a shortcut, but some plugins may not support it. So please try the full `/register`.

Then, you can try to log in with the same nickname as a normal player and try to register yourself.

If it doesn't help, I am afraid I can not help with it anymore, because as I said, the problem is on the server, not in my app.

Thanks.

**Comment by ByYaoTang** [comment]
> 



> 感谢您发送输出。
> 
> 很明显，错误消息来自服务器，因为它的前缀为 。请确保您使用的是正确的命令。服务器说你应该使用，但你只使用，我知道这是一个快捷方式，但有些插件可能不支持它。因此，请尝试完整的.`CHAT |``/register``/reg``/register`
> 
> 然后，您可以尝试使用与普通玩家相同的昵称登录，并尝试注册自己。
> 
> 如果它没有帮助，恐怕我不能再帮助它了，因为正如我所说，问题出在我的服务器上，而不是在我的应用程序中。
> 
> 谢谢。



> Thanks for sending the output.
> 
> It is clear that the error message comes from the server, as it is prefixed with `CHAT |`. Please make sure, you are using the right command. The server says you should use `/register`, but you are using `/reg` only, I know this is a shortcut, but some plugins may not support it. So please try the full `/register`.
> 
> Then, you can try to log in with the same nickname as a normal player and try to register yourself.
> 
> If it doesn't help, I am afraid I can not help with it anymore, because as I said, the problem is on the server, not in my app.
> 
> Thanks.

I'll try again How do I use assigned names and mobile

**Comment by ByYaoTang** [comment]
> Thanks for sending the output.
> 
> It is clear that the error message comes from the server, as it is prefixed with `CHAT |`. Please make sure, you are using the right command. The server says you should use `/register`, but you are using `/reg` only, I know this is a shortcut, but some plugins may not support it. So please try the full `/register`.
> 
> Then, you can try to log in with the same nickname as a normal player and try to register yourself.
> 
> If it doesn't help, I am afraid I can not help with it anymore, because as I said, the problem is on the server, not in my app.
> 
> Thanks.

I'll try again,How do I use assigned names and move

**Comment by ByYaoTang** [comment]
Ready to use! But I ended the robot automatically after one minute. How can I keep the robot in the server and mobile position

**Comment by crpmax** [comment]
I don't understand exactly what you are referring to, but if you mean that the bot was kicked from the server after one minute, it is, probably, again something on the server. Probably due to AFK, because the bot is not moving. Or it could be because the bot was stuck in the air and the server kicked it for flying.
I plan to implement optional gravity and bot movement in the future.

**Comment by ByYaoTang** [comment]
oh ok! thank you for your reply I got help
