### ISSUE TITLE
Bot disconnected from server immediately after they connected.

### ISSUE THREAD

**Issue by solitary-sails** [crpmax/mc-bots#54]
# Informations
OS:Windows 10
JRE:Azul zulu JRE 11.60.19(11.0.17),64-bit
mc-bots version:1.2.3
Command Used: java -jar .\mc-bots.jar -s 192.168.3.2 -p BOT_ -d 4000 5000 -c 30
# Console Output
![Snipaste_2022-12-15_21-15-33](https://user-images.githubusercontent.com/52939914/207869974-551e11e5-1512-46c5-9d40-1b392ba963f6.png)

**Comment by cevxl** [comment]
Can you send the code again, but in a code block? I'll try to fix it and open a pull request.

**Comment by crpmax** [comment]
Hello,
it looks like the server sends the client some packet SetTitleTextPacket and the bot crashes.
Are there any titles shown on your server on login?
You can try disabling the titles or changing them so they are not empty.

This issue was tracked here:
https://github.com/KyoriPowered/adventure/issues/447
