### ISSUE TITLE
[Feature Request] Fabirc Server Support

### ISSUE THREAD

**Issue by douglasg14b** [crpmax/mc-bots#77]
Essentially as the title says, support for fabric server and fabric loader!

**Comment by CamperSamu** [comment]
This is actually needed since the bots fail to join servers with serverside mods and specific patches to make the vanilla client seamless like [PolyMc](https://github.com/TheEpicBlock/PolyMc/).

I want to test my server against a bot wave but the bots fail to join, I tried everything (proxy, viaver...) but I can't get it to work.

**Comment by crpmax** [comment]
Hello, sadly the issue is the same as with Forge.
https://github.com/crpmax/mc-bots/issues/67#issuecomment-1571819129

**Comment by CamperSamu** [comment]
The weird part is that in my configuration Fabric packets are blocked, and vanilla clients are working fine.
A workaround for a setup like mine should be feasable.

**Comment by crpmax** [comment]
I am sorry, but support for Fabric is currently not in my hands right now.
I plan to rewrite version 2 with different MC protocol library, that should support it.

**Comment by jaynotgay** [comment]
Please support fabric!
